apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    app: aws-app-provisioner
  name: aws-app-provisioner
  namespace: platform-provisioner-tools
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: aws-app-provisioner
    labels:
      app: aws-app-provisioner
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: aws-app-provisioner
    labels:
      app: aws-app-provisioner
      name: aws-app-provisioner
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'aws-app-provisioner:latest'
    resources:
      limits:
        cpu: '1'
        memory: 2Gi
    source:
      git:
        ref: main
        uri: 'https://github.com/prabhukiran9999/pr-script.git'
      type: Git
    strategy:
      dockerStrategy:
        env:
        - name: BUILD_LOGLEVEL
          value: "5"
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
- description: |
    The name assigned to all of the objects defined in this template.
    You should keep this as default unless your know what your doing.
  displayName: Name
  name: NAME
  required: true
  value: platsrv-registry
- description: |
    The URL to your GIT repo, don't use the this default unless
    your just experimenting.
  displayName: Git Repo URL
  name: GIT_REPO_URL
  value: https://github.com/prabhukiran9999/pr-script.git
  required: true
- description: The git reference or branch.
  displayName: Git Reference
  name: GIT_REF
  required: true
  value: main
- description: The resources CPU limit (in cores) for this build.
  displayName: Resources CPU Limit
  name: CPU_LIMIT
  required: true
  value: "500m"
- description: The resources CPU request (in cores) for this build.
  displayName: Resources CPU Request
  name: CPU_REQUEST
  required: true
  value: "250m"
- description: The resources Memory limit (in Mi, Gi, etc) for this build.
  displayName: Resources Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 1Gi
- description: The resources Memory request (in Mi, Gi, etc) for this build.
  displayName: Resources Memory Request
  name: MEMORY_REQUEST
  required: true
  value: 500Mi
- description: The name of the source image.
  displayName: Source Image Name
  name: SOURCE_IMAGE_NAME
  value: 'ubuntu'
  required: true
- description: The openshift project where builds and target images are stored.
  displayName: Build Project
  name: SOURCE_IMAGE_NAMESPACE
  value: 'platform-provisioner-tools'
  required: true
- description: The tag given to the built image.
  displayName: Output Image Tag
  name: OUTPUT_IMAGE_TAG
  required: true
  value: v1